In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])


In [3]:
type(arr)


numpy.ndarray

In [4]:
arr[0]
arr[2]


np.int64(30)

In [5]:
arr[1:4]


array([20, 30, 40])

In [14]:
arr * 2


array([ 20,  40,  60,  80, 100])

In [16]:
np.sum(arr)



np.int64(150)

In [17]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


In [18]:
np.sum(matrix, axis=0)

array([5, 7, 9])

In [19]:
np.sum(matrix, axis=1)

array([ 6, 15])

In [20]:
arr2 = np.array([1, 2, 3, 4])



In [21]:
arr2.reshape(2, 2)


array([[1, 2],
       [3, 4]])

In [22]:
arr + 10


array([20, 30, 40, 50, 60])

In [24]:
np.save("my_array.npy", arr)


In [25]:
loaded_arr = np.load("my_array.npy")
loaded_arr


array([10, 20, 30, 40, 50])